# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphics.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(589, 360)
        self.widget = PlotWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 10, 541, 221))
        self.widget.setObjectName("widget")
        self.func_input = QtWidgets.QLineEdit(Form)
        self.func_input.setGeometry(QtCore.QRect(290, 240, 291, 21))
        self.func_input.setObjectName("func_input")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 240, 201, 21))
        self.label.setObjectName("label")
        self.draw_button = QtWidgets.QPushButton(Form)
        self.draw_button.setGeometry(QtCore.QRect(300, 270, 261, 23))
        self.draw_button.setObjectName("draw_button")
        self.error_messenger = QtWidgets.QLabel(Form)
        self.error_messenger.setGeometry(QtCore.QRect(110, 310, 421, 20))
        self.error_messenger.setText("")
        self.error_messenger.setObjectName("error_messenger")
        self.green = QtWidgets.QRadioButton(Form)
        self.green.setGeometry(QtCore.QRect(20, 270, 80, 18))
        self.green.setObjectName("green")
        self.red = QtWidgets.QRadioButton(Form)
        self.red.setGeometry(QtCore.QRect(120, 270, 80, 18))
        self.red.setChecked(True)
        self.red.setObjectName("red")
        self.blue = QtWidgets.QRadioButton(Form)
        self.blue.setGeometry(QtCore.QRect(190, 270, 80, 18))
        self.blue.setObjectName("blue")
        self.exit_button = QtWidgets.QPushButton(Form)
        self.exit_button.setGeometry(QtCore.QRect(20, 300, 71, 41))
        self.exit_button.setObjectName("exit_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Введите функцию вида f(x):"))
        self.draw_button.setText(_translate("Form", "Draw"))
        self.green.setText(_translate("Form", "Green"))
        self.red.setText(_translate("Form", "Red"))
        self.blue.setText(_translate("Form", "Blue"))
        self.exit_button.setText(_translate("Form", "Exit"))
from pyqtgraph import PlotWidget
