# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(395, 351)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 0, 181, 61))
        self.label.setObjectName("label")
        self.button_to_calculator = QtWidgets.QPushButton(self.centralwidget)
        self.button_to_calculator.setGeometry(QtCore.QRect(30, 50, 101, 51))
        self.button_to_calculator.setObjectName("button_to_calculator")
        self.button_to_graphics = QtWidgets.QPushButton(self.centralwidget)
        self.button_to_graphics.setGeometry(QtCore.QRect(250, 50, 121, 51))
        self.button_to_graphics.setObjectName("button_to_graphics")
        self.button_to_polynoms = QtWidgets.QPushButton(self.centralwidget)
        self.button_to_polynoms.setGeometry(QtCore.QRect(80, 130, 221, 61))
        self.button_to_polynoms.setObjectName("button_to_polynoms")
        self.button_to_test = QtWidgets.QPushButton(self.centralwidget)
        self.button_to_test.setGeometry(QtCore.QRect(100, 230, 181, 61))
        self.button_to_test.setObjectName("button_to_test")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 395, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Math Elf</span></p></body></html>"))
        self.button_to_calculator.setText(_translate("MainWindow", "Calculator"))
        self.button_to_graphics.setText(_translate("MainWindow", "Graphics"))
        self.button_to_polynoms.setText(_translate("MainWindow", "Polynoms"))
        self.button_to_test.setText(_translate("MainWindow", "Testing your knowledge"))
